### ISSUE TITLE
[Question] ResNet pre actiovation blocks

### ISSUE THREAD

**Issue by pi-tau** [phlippe/uvadlc_notebooks#107]
**Tutorial**: 5

Hi @phlippe
In cells 23 and 25 from Tutorial 5 you define the pre-activation Residual block, and the full ResNet respectively.
My question is regarding the definition of the `input_net` and `output_net` in cell 25.
I was reading the Pre-activation [paper](https://arxiv.org/abs/1603.05027) and the authors mention in the appendix (at the very last page) that they adopt an extra activation right **before** the first residual block and right **after** the last one.
So shouldn't there be two extra BN + ReLU layers?

Adding BN+ReLU right after the last Pre-act ResBlock and just before the Adaptive pooling layer seems like a good idea, because I think that we are actually missing a non-linearity between the last convolution and the linear layer.

Adding BN+ReLU (or maybe only ReLU) right after the `input_net` and before the first Pre-act ResBlock is not that intuitive for me, I think the concern is that in the original ResNet design the features from the first convolution are modified with non-linearity and only then the residual blocks are applied. While in the pre-activation architecture we will actually propagate the non-modified features from the first convolution all the way to the end. However, in the first ResBlock we will actually end up applying BN+ReLU for the second time consecutively, but I have no idea if that would be a problem. I would guess that in their implementation their first Pre-activation ResBlock is probably lacking the BN+ReLU in the beginning in order not to apply them twice (i.e., FirstResBlock =[Conv + BN +ReLU + Conv])?

And finally, the authors mention that they also use pre-activation in their subsamling shortcut (e.g. `self.downsample` in Cell 23), but strangely they explicitly say that they are applying this for the **bottleneck** ResBlocks, bagging the question "what about normal `3x3` + `3x3` ResBlocks"? Should we use the pre-activation for them as well, or apply only a `1x1` convolution (`self.downsample` in Cell 22) ?

I am pretty sure that these details would not have much effect, especially on the scale of CIFAR10 problems, but still I found it interesting what should the most correct approach be, and what have you seen in practice.

Thanks :)

**Comment by phlippe** [comment]
Hi @pi-tau, in general, the models presented here are based on the common 'modern' implementations of them and not necessarily 1-to-1 as in the original papers. Regarding your specific questions:
* **Activation before first ResNet block**: that is true, if we would apply an activation there, the first block would essentially apply a BN+ReLU on an output of just another ReLU. This is not recommended since you zero out a lot more neurons and does not have any apparent benefit (at least to me). In most current 'modern' Pre-ResNet implementations, you don't have this layer either.
* **Activation after last ResNet block**: you are right that sometimes an additional activation can be used before the pooling layer. However, I often see that if you do pooling, an activation function is often not needed. I had actually trained multiple versions of the ResNet with the extra final activation, and commonly got worse results. Thus, I decided to stick with the one without activation here.
* **Downsample layers**: in general, you only apply the `self.downsample` part when you need to change the feature dimension. For normal ResBlocks with same input+output features, no 1x1 conv is needed.

**Comment by pi-tau** [comment]
Hi, this is quite interesting that the extra final activation worsens results. Thanks for sharing.
