### ISSUE TITLE
Tutorial 16: Few Shot Sampling Tasks Clarification

### ISSUE THREAD

**Issue by pandeydeep9** [phlippe/uvadlc_notebooks#17]
Hi!

Thank you very much for creating this great resource and making it publicly available. It is very helpful.

One thing is that for the few shot tasks, the classes should be distinct within a task. Looking at the code at `class FewShotBatchSampler`, I think the current sampler does not ensure that  Currently, I think the classes selected within a task could be the same.

For e.g. say I have 10 classes (with 20,000 images/class) in the training set and I want to sample 5-way 4-shot training tasks. I think the current sampler may choose the same class multiple times within the same task. I think randomly selecting `N_way` classes from `self.class_list` may not be accurate. Maybe  `class_batch = self.class_list[it*self.N_way:(it+1)*self.N_way]  # Select N classes for the batch` could be changed to correct for this.

Please correct me if I've misunderstood something.
Thanks

**Comment by phlippe** [comment]
Hi, thanks for your question! You are right that there is a small chance that in a training batch, we select a task with twice the same class. However, this was a design choice that I actively made during implementing this notebook. The reason for this is four-folded:
1. Firstly, creating a random order in which no class is picked twice in a task while keeping the number of times each class is sampled during an epoch constant, can be quite an overhead, depending on how sophisticated one would want to make the code. Not using this simplifies the code quite a bit and makes it easier to understand.
2. Secondly, both the ProtoNet and ProtoMAML implementation actually have no problem with having the same class twice in a batch. For instance, in a 5-way 4-shot training task, if the first and second class are identical, both ProtoNet and ProtoMAML view this batch as a 4-way classification, with the first class having 8 shots and all others 4. The same code handles this setting without any adjustments necessary, and therefore trains with it properly. 
3. Thirdly, with 80 training class in the example dataset, this scenario happens quite rarely and has almost no effect in training.
4. Finally, having such batches occasionally in the training can actually have a regularization effect. It ensures that the model does not bias itself in any way to always having exactly 5 classes, and thus helps slightly in also performing well in smaller sets. 

Overall, I decided to allow these double-samples of classes for having a simpler code, and seeing no noticeable difference in training. Still, thanks for pointing it out, since I haven't actively addressed it in the explanation of the notebook, and will add it in an update!

**Comment by pandeydeep9** [comment]
Thanks for the clarification. It helps a lot.
