### ISSUE TITLE
A bug in tutorial 7

### ISSUE THREAD

**Issue by kohanlee1995** [phlippe/uvadlc_notebooks#5]
**Tutorial**: 7

**Describe the bug**
Thanks for such an explicit tutorial for GNN.
In the code section of GATLayer function,
```
edge_indices_row = edges[:,0] * batch_size + edges[:,1]
edge_indices_col = edges[:,0] * batch_size + edges[:,2]
```
I'm not very sure whether this is a bug or I misunderstand it.
I think ```batch_size``` should be replaced with ```num_nodes``` to get the correct index.

**Comment by phlippe** [comment]
Hi, thanks for raising the issue! You are absolutely correct, that should have been `num_nodes` instead of `batch_size`. When we flatten the node features, we need to take a step size of `num_nodes` to get from the nodes in batch 0 to the nodes in batch 1, not `batch_size`. The newly pushed version corrects this bug.
