### ISSUE TITLE
Another dataset

### ISSUE THREAD

**Issue by mehrshadmmt** [phlippe/uvadlc_notebooks#50]
Hello, how can I use some another dataset like, cifar100 or MNIST, in tutorial 15?

**Comment by phlippe** [comment]
Hi, the code is written relatively dataset-agnostic. The main changes for a different dataset need to be done in cell 3, where you can load your preferred dataset from torchvision. In cell 10, you need to adjust the two parameters `num_classes` (100 for CIFAR100, MNIST still 10) and `num_patches` (49 for MNIST since we get a 7x7 grid, CIFAR100 will have 64 as CIFAR10). With these changes, you are ready to train the Vision Transformer on your dataset.

**Comment by mehrshadmmt** [comment]
Thanks a lot for your reply....
