### ISSUE TITLE
suggestion re content  for tutorial 5 (CNNs)

### ISSUE THREAD

**Issue by murphyk** [phlippe/uvadlc_notebooks#87]
I suggest you drop GoogleNet/Inception from https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/JAX/tutorial5/Inception_ResNet_DenseNet.html, since no one really uses this anymore (except for FID score!), and it's pretty complicated. WDYT?

**Comment by murphyk** [comment]
Actually, in view of the good performance of googlenet, maybe it is worth keeping? :)
<img width="1213" alt="Screenshot 2023-03-19 at 3 02 18 PM" src="https://user-images.githubusercontent.com/4632336/226212347-4d2be2a9-f071-47e1-944d-611c48179f16.png">

**Comment by phlippe** [comment]
We mostly kept it in because in the lectures of our Deep Learning course, we give a bit of an overview of the different CNNs that were proposed over time, and the term 'GoogleNet' or 'Inception' is still one that you may come across in some areas (FID, Inception-Resnet, etc.). In the end, one can also skip this section while reading the tutorial, since the sections of the different networks are mostly independent :)
